# pubspec.yaml

name: games_reviews

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: any
  shelf_router: any
  shelf_static: any
  mysql1: any
  crypt: ^4.2.1
  jaguar_jwt: any
  jwt_decoder: ^2.0.1
  dotenv: ^3.0.0

dev_dependencies: 
  lints: ^1.0.1
